[features]
seeds = false
skip-lint = false
[programs.localnet]
tree = "8H96sxi32XpxsJF2DjfXuiTNvTADabxoFVY9SWLS5fLC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/alan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
